// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChannelAvatarGetList.net.iGap.proto

package net.iGap.proto;

public final class ProtoChannelAvatarGetList {
  private ProtoChannelAvatarGetList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChannelAvatarGetListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.iGap.proto.ChannelAvatarGetList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return The request.
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    long getRoomId();
  }
  /**
   * Protobuf type {@code net.iGap.proto.ChannelAvatarGetList}
   */
  public static final class ChannelAvatarGetList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.iGap.proto.ChannelAvatarGetList)
      ChannelAvatarGetListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChannelAvatarGetList.newBuilder() to construct.
    private ChannelAvatarGetList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelAvatarGetList() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChannelAvatarGetList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChannelAvatarGetList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList.class, net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return The request.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int ROOM_ID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    @java.lang.Override
    public long getRoomId() {
      return roomId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (roomId_ != 0L) {
        output.writeUInt64(2, roomId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, roomId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList other = (net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (getRoomId()
          != other.getRoomId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.iGap.proto.ChannelAvatarGetList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.iGap.proto.ChannelAvatarGetList)
        net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList.class, net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList.Builder.class);
      }

      // Construct using net.iGap.net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        roomId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetList_descriptor;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList getDefaultInstanceForType() {
        return net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList.getDefaultInstance();
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList build() {
        net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList buildPartial() {
        net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList result = new net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.roomId_ = roomId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList) {
          return mergeFrom((net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList other) {
        if (other == net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       * @return The request.
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long roomId_ ;
      /**
       * <code>uint64 room_id = 2;</code>
       * @return The roomId.
       */
      @java.lang.Override
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.iGap.proto.ChannelAvatarGetList)
    }

    // @@protoc_insertion_point(class_scope:net.iGap.proto.ChannelAvatarGetList)
    private static final net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList();
    }

    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChannelAvatarGetList>
        PARSER = new com.google.protobuf.AbstractParser<ChannelAvatarGetList>() {
      @java.lang.Override
      public ChannelAvatarGetList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelAvatarGetList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChannelAvatarGetList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelAvatarGetList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChannelAvatarGetListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.iGap.proto.ChannelAvatarGetListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return The response.
     */
    net.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    java.util.List<net.iGap.proto.ProtoGlobal.Avatar> 
        getAvatarList();
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.Avatar getAvatar(int index);
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    int getAvatarCount();
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    java.util.List<? extends net.iGap.proto.ProtoGlobal.AvatarOrBuilder> 
        getAvatarOrBuilderList();
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.AvatarOrBuilder getAvatarOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.iGap.proto.ChannelAvatarGetListResponse}
   */
  public static final class ChannelAvatarGetListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.iGap.proto.ChannelAvatarGetListResponse)
      ChannelAvatarGetListResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChannelAvatarGetListResponse.newBuilder() to construct.
    private ChannelAvatarGetListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelAvatarGetListResponse() {
      avatar_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChannelAvatarGetListResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChannelAvatarGetListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                avatar_ = new java.util.ArrayList<net.iGap.proto.ProtoGlobal.Avatar>();
                mutable_bitField0_ |= 0x00000001;
              }
              avatar_.add(
                  input.readMessage(net.iGap.proto.ProtoGlobal.Avatar.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          avatar_ = java.util.Collections.unmodifiableList(avatar_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse.class, net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return The response.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int AVATAR_FIELD_NUMBER = 2;
    private java.util.List<net.iGap.proto.ProtoGlobal.Avatar> avatar_;
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    @java.lang.Override
    public java.util.List<net.iGap.proto.ProtoGlobal.Avatar> getAvatarList() {
      return avatar_;
    }
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends net.iGap.proto.ProtoGlobal.AvatarOrBuilder> 
        getAvatarOrBuilderList() {
      return avatar_;
    }
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    @java.lang.Override
    public int getAvatarCount() {
      return avatar_.size();
    }
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoGlobal.Avatar getAvatar(int index) {
      return avatar_.get(index);
    }
    /**
     * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoGlobal.AvatarOrBuilder getAvatarOrBuilder(
        int index) {
      return avatar_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      for (int i = 0; i < avatar_.size(); i++) {
        output.writeMessage(2, avatar_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      for (int i = 0; i < avatar_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, avatar_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse other = (net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!getAvatarList()
          .equals(other.getAvatarList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (getAvatarCount() > 0) {
        hash = (37 * hash) + AVATAR_FIELD_NUMBER;
        hash = (53 * hash) + getAvatarList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.iGap.proto.ChannelAvatarGetListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.iGap.proto.ChannelAvatarGetListResponse)
        net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetListResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse.class, net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse.Builder.class);
      }

      // Construct using net.iGap.net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAvatarFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        if (avatarBuilder_ == null) {
          avatar_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          avatarBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoChannelAvatarGetList.internal_static_proto_ChannelAvatarGetListResponse_descriptor;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse getDefaultInstanceForType() {
        return net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse build() {
        net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse buildPartial() {
        net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse result = new net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse(this);
        int from_bitField0_ = bitField0_;
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (avatarBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            avatar_ = java.util.Collections.unmodifiableList(avatar_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.avatar_ = avatar_;
        } else {
          result.avatar_ = avatarBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse) {
          return mergeFrom((net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse other) {
        if (other == net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (avatarBuilder_ == null) {
          if (!other.avatar_.isEmpty()) {
            if (avatar_.isEmpty()) {
              avatar_ = other.avatar_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAvatarIsMutable();
              avatar_.addAll(other.avatar_);
            }
            onChanged();
          }
        } else {
          if (!other.avatar_.isEmpty()) {
            if (avatarBuilder_.isEmpty()) {
              avatarBuilder_.dispose();
              avatarBuilder_ = null;
              avatar_ = other.avatar_;
              bitField0_ = (bitField0_ & ~0x00000001);
              avatarBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAvatarFieldBuilder() : null;
            } else {
              avatarBuilder_.addAllMessages(other.avatar_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private net.iGap.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       * @return The response.
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private java.util.List<net.iGap.proto.ProtoGlobal.Avatar> avatar_ =
        java.util.Collections.emptyList();
      private void ensureAvatarIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          avatar_ = new java.util.ArrayList<net.iGap.proto.ProtoGlobal.Avatar>(avatar_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.Avatar, net.iGap.proto.ProtoGlobal.Avatar.Builder, net.iGap.proto.ProtoGlobal.AvatarOrBuilder> avatarBuilder_;

      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public java.util.List<net.iGap.proto.ProtoGlobal.Avatar> getAvatarList() {
        if (avatarBuilder_ == null) {
          return java.util.Collections.unmodifiableList(avatar_);
        } else {
          return avatarBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public int getAvatarCount() {
        if (avatarBuilder_ == null) {
          return avatar_.size();
        } else {
          return avatarBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.Avatar getAvatar(int index) {
        if (avatarBuilder_ == null) {
          return avatar_.get(index);
        } else {
          return avatarBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder setAvatar(
          int index, net.iGap.proto.ProtoGlobal.Avatar value) {
        if (avatarBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAvatarIsMutable();
          avatar_.set(index, value);
          onChanged();
        } else {
          avatarBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder setAvatar(
          int index, net.iGap.proto.ProtoGlobal.Avatar.Builder builderForValue) {
        if (avatarBuilder_ == null) {
          ensureAvatarIsMutable();
          avatar_.set(index, builderForValue.build());
          onChanged();
        } else {
          avatarBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder addAvatar(net.iGap.proto.ProtoGlobal.Avatar value) {
        if (avatarBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAvatarIsMutable();
          avatar_.add(value);
          onChanged();
        } else {
          avatarBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder addAvatar(
          int index, net.iGap.proto.ProtoGlobal.Avatar value) {
        if (avatarBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAvatarIsMutable();
          avatar_.add(index, value);
          onChanged();
        } else {
          avatarBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder addAvatar(
          net.iGap.proto.ProtoGlobal.Avatar.Builder builderForValue) {
        if (avatarBuilder_ == null) {
          ensureAvatarIsMutable();
          avatar_.add(builderForValue.build());
          onChanged();
        } else {
          avatarBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder addAvatar(
          int index, net.iGap.proto.ProtoGlobal.Avatar.Builder builderForValue) {
        if (avatarBuilder_ == null) {
          ensureAvatarIsMutable();
          avatar_.add(index, builderForValue.build());
          onChanged();
        } else {
          avatarBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder addAllAvatar(
          java.lang.Iterable<? extends net.iGap.proto.ProtoGlobal.Avatar> values) {
        if (avatarBuilder_ == null) {
          ensureAvatarIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, avatar_);
          onChanged();
        } else {
          avatarBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder clearAvatar() {
        if (avatarBuilder_ == null) {
          avatar_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          avatarBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public Builder removeAvatar(int index) {
        if (avatarBuilder_ == null) {
          ensureAvatarIsMutable();
          avatar_.remove(index);
          onChanged();
        } else {
          avatarBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.Avatar.Builder getAvatarBuilder(
          int index) {
        return getAvatarFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.AvatarOrBuilder getAvatarOrBuilder(
          int index) {
        if (avatarBuilder_ == null) {
          return avatar_.get(index);  } else {
          return avatarBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public java.util.List<? extends net.iGap.proto.ProtoGlobal.AvatarOrBuilder> 
           getAvatarOrBuilderList() {
        if (avatarBuilder_ != null) {
          return avatarBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(avatar_);
        }
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.Avatar.Builder addAvatarBuilder() {
        return getAvatarFieldBuilder().addBuilder(
            net.iGap.proto.ProtoGlobal.Avatar.getDefaultInstance());
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.Avatar.Builder addAvatarBuilder(
          int index) {
        return getAvatarFieldBuilder().addBuilder(
            index, net.iGap.proto.ProtoGlobal.Avatar.getDefaultInstance());
      }
      /**
       * <code>repeated .net.iGap.proto.Avatar avatar = 2;</code>
       */
      public java.util.List<net.iGap.proto.ProtoGlobal.Avatar.Builder> 
           getAvatarBuilderList() {
        return getAvatarFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.Avatar, net.iGap.proto.ProtoGlobal.Avatar.Builder, net.iGap.proto.ProtoGlobal.AvatarOrBuilder> 
          getAvatarFieldBuilder() {
        if (avatarBuilder_ == null) {
          avatarBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.iGap.proto.ProtoGlobal.Avatar, net.iGap.proto.ProtoGlobal.Avatar.Builder, net.iGap.proto.ProtoGlobal.AvatarOrBuilder>(
                  avatar_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          avatar_ = null;
        }
        return avatarBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.iGap.proto.ChannelAvatarGetListResponse)
    }

    // @@protoc_insertion_point(class_scope:net.iGap.proto.ChannelAvatarGetListResponse)
    private static final net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse();
    }

    public static net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChannelAvatarGetListResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChannelAvatarGetListResponse>() {
      @java.lang.Override
      public ChannelAvatarGetListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelAvatarGetListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChannelAvatarGetListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelAvatarGetListResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.iGap.proto.ProtoChannelAvatarGetList.ChannelAvatarGetListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChannelAvatarGetList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChannelAvatarGetList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChannelAvatarGetListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChannelAvatarGetListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ChannelAvatarGetList.net.iGap.proto\022\005proto\032\rReq" +
      "uest.net.iGap.proto\032\016Response.net.iGap.proto\032\014Global.net.iGap.proto" +
      "\"H\n\024ChannelAvatarGetList\022\037\n\007request\030\001 \001(" +
      "\0132\016.net.iGap.proto.Request\022\017\n\007room_id\030\002 \001(\004\"`\n\034Ch" +
      "annelAvatarGetListResponse\022!\n\010response\030\001" +
      " \001(\0132\017.net.iGap.proto.Response\022\035\n\006avatar\030\002 \003(\0132\r." +
      "net.iGap.proto.AvatarB3\n\026net.iGap.protoB\031" +
      "ProtoChannelAvatarGetListb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.iGap.proto.ProtoRequest.getDescriptor(),
          net.iGap.proto.ProtoResponse.getDescriptor(),
          net.iGap.proto.ProtoGlobal.getDescriptor(),
        });
    internal_static_proto_ChannelAvatarGetList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ChannelAvatarGetList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChannelAvatarGetList_descriptor,
        new java.lang.String[] { "Request", "RoomId", });
    internal_static_proto_ChannelAvatarGetListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ChannelAvatarGetListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChannelAvatarGetListResponse_descriptor,
        new java.lang.String[] { "Response", "Avatar", });
    net.iGap.proto.ProtoRequest.getDescriptor();
    net.iGap.proto.ProtoResponse.getDescriptor();
    net.iGap.proto.ProtoGlobal.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
