// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserIVandGetActivities.net.iGap.proto

package net.iGap.proto;

public final class ProtoUserIVandGetActivities {
  private ProtoUserIVandGetActivities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserIVandGetActivitiesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.iGap.proto.UserIVandGetActivities)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return The request.
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>.net.iGap.proto.Pagination pagination = 2;</code>
     * @return Whether the pagination field is set.
     */
    boolean hasPagination();
    /**
     * <code>.net.iGap.proto.Pagination pagination = 2;</code>
     * @return The pagination.
     */
    net.iGap.proto.ProtoGlobal.Pagination getPagination();
    /**
     * <code>.net.iGap.proto.Pagination pagination = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.PaginationOrBuilder getPaginationOrBuilder();
  }
  /**
   * Protobuf type {@code net.iGap.proto.UserIVandGetActivities}
   */
  public static final class UserIVandGetActivities extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.iGap.proto.UserIVandGetActivities)
      UserIVandGetActivitiesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserIVandGetActivities.newBuilder() to construct.
    private UserIVandGetActivities(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserIVandGetActivities() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserIVandGetActivities();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserIVandGetActivities(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              net.iGap.proto.ProtoGlobal.Pagination.Builder subBuilder = null;
              if (pagination_ != null) {
                subBuilder = pagination_.toBuilder();
              }
              pagination_ = input.readMessage(net.iGap.proto.ProtoGlobal.Pagination.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pagination_);
                pagination_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivities_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivities_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities.class, net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return The request.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int PAGINATION_FIELD_NUMBER = 2;
    private net.iGap.proto.ProtoGlobal.Pagination pagination_;
    /**
     * <code>.net.iGap.proto.Pagination pagination = 2;</code>
     * @return Whether the pagination field is set.
     */
    @java.lang.Override
    public boolean hasPagination() {
      return pagination_ != null;
    }
    /**
     * <code>.net.iGap.proto.Pagination pagination = 2;</code>
     * @return The pagination.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoGlobal.Pagination getPagination() {
      return pagination_ == null ? net.iGap.proto.ProtoGlobal.Pagination.getDefaultInstance() : pagination_;
    }
    /**
     * <code>.net.iGap.proto.Pagination pagination = 2;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoGlobal.PaginationOrBuilder getPaginationOrBuilder() {
      return getPagination();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (pagination_ != null) {
        output.writeMessage(2, getPagination());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (pagination_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPagination());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities other = (net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (hasPagination() != other.hasPagination()) return false;
      if (hasPagination()) {
        if (!getPagination()
            .equals(other.getPagination())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasPagination()) {
        hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
        hash = (53 * hash) + getPagination().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.iGap.proto.UserIVandGetActivities}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.iGap.proto.UserIVandGetActivities)
        net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivities_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivities_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities.class, net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities.Builder.class);
      }

      // Construct using net.iGap.net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        if (paginationBuilder_ == null) {
          pagination_ = null;
        } else {
          pagination_ = null;
          paginationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivities_descriptor;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities getDefaultInstanceForType() {
        return net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities.getDefaultInstance();
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities build() {
        net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities buildPartial() {
        net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities result = new net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (paginationBuilder_ == null) {
          result.pagination_ = pagination_;
        } else {
          result.pagination_ = paginationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities) {
          return mergeFrom((net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities other) {
        if (other == net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasPagination()) {
          mergePagination(other.getPagination());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       * @return The request.
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private net.iGap.proto.ProtoGlobal.Pagination pagination_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.Pagination, net.iGap.proto.ProtoGlobal.Pagination.Builder, net.iGap.proto.ProtoGlobal.PaginationOrBuilder> paginationBuilder_;
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       * @return Whether the pagination field is set.
       */
      public boolean hasPagination() {
        return paginationBuilder_ != null || pagination_ != null;
      }
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       * @return The pagination.
       */
      public net.iGap.proto.ProtoGlobal.Pagination getPagination() {
        if (paginationBuilder_ == null) {
          return pagination_ == null ? net.iGap.proto.ProtoGlobal.Pagination.getDefaultInstance() : pagination_;
        } else {
          return paginationBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       */
      public Builder setPagination(net.iGap.proto.ProtoGlobal.Pagination value) {
        if (paginationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pagination_ = value;
          onChanged();
        } else {
          paginationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       */
      public Builder setPagination(
          net.iGap.proto.ProtoGlobal.Pagination.Builder builderForValue) {
        if (paginationBuilder_ == null) {
          pagination_ = builderForValue.build();
          onChanged();
        } else {
          paginationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       */
      public Builder mergePagination(net.iGap.proto.ProtoGlobal.Pagination value) {
        if (paginationBuilder_ == null) {
          if (pagination_ != null) {
            pagination_ =
              net.iGap.proto.ProtoGlobal.Pagination.newBuilder(pagination_).mergeFrom(value).buildPartial();
          } else {
            pagination_ = value;
          }
          onChanged();
        } else {
          paginationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       */
      public Builder clearPagination() {
        if (paginationBuilder_ == null) {
          pagination_ = null;
          onChanged();
        } else {
          pagination_ = null;
          paginationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.Pagination.Builder getPaginationBuilder() {
        
        onChanged();
        return getPaginationFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.PaginationOrBuilder getPaginationOrBuilder() {
        if (paginationBuilder_ != null) {
          return paginationBuilder_.getMessageOrBuilder();
        } else {
          return pagination_ == null ?
              net.iGap.proto.ProtoGlobal.Pagination.getDefaultInstance() : pagination_;
        }
      }
      /**
       * <code>.net.iGap.proto.Pagination pagination = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.Pagination, net.iGap.proto.ProtoGlobal.Pagination.Builder, net.iGap.proto.ProtoGlobal.PaginationOrBuilder>
          getPaginationFieldBuilder() {
        if (paginationBuilder_ == null) {
          paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoGlobal.Pagination, net.iGap.proto.ProtoGlobal.Pagination.Builder, net.iGap.proto.ProtoGlobal.PaginationOrBuilder>(
                  getPagination(),
                  getParentForChildren(),
                  isClean());
          pagination_ = null;
        }
        return paginationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.iGap.proto.UserIVandGetActivities)
    }

    // @@protoc_insertion_point(class_scope:net.iGap.proto.UserIVandGetActivities)
    private static final net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities();
    }

    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserIVandGetActivities>
        PARSER = new com.google.protobuf.AbstractParser<UserIVandGetActivities>() {
      @java.lang.Override
      public UserIVandGetActivities parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserIVandGetActivities(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserIVandGetActivities> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserIVandGetActivities> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivities getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserIVandGetActivitiesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.iGap.proto.UserIVandGetActivitiesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return The response.
     */
    net.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    java.util.List<net.iGap.proto.ProtoGlobal.IVandActivity>
        getActivitiesList();
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.IVandActivity getActivities(int index);
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    int getActivitiesCount();
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    java.util.List<? extends net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder>
        getActivitiesOrBuilderList();
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder getActivitiesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.iGap.proto.UserIVandGetActivitiesResponse}
   */
  public static final class UserIVandGetActivitiesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.iGap.proto.UserIVandGetActivitiesResponse)
      UserIVandGetActivitiesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserIVandGetActivitiesResponse.newBuilder() to construct.
    private UserIVandGetActivitiesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserIVandGetActivitiesResponse() {
      activities_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserIVandGetActivitiesResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserIVandGetActivitiesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                activities_ = new java.util.ArrayList<net.iGap.proto.ProtoGlobal.IVandActivity>();
                mutable_bitField0_ |= 0x00000001;
              }
              activities_.add(
                  input.readMessage(net.iGap.proto.ProtoGlobal.IVandActivity.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          activities_ = java.util.Collections.unmodifiableList(activities_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivitiesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivitiesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse.class, net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return The response.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int ACTIVITIES_FIELD_NUMBER = 2;
    private java.util.List<net.iGap.proto.ProtoGlobal.IVandActivity> activities_;
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    @java.lang.Override
    public java.util.List<net.iGap.proto.ProtoGlobal.IVandActivity> getActivitiesList() {
      return activities_;
    }
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder>
        getActivitiesOrBuilderList() {
      return activities_;
    }
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    @java.lang.Override
    public int getActivitiesCount() {
      return activities_.size();
    }
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoGlobal.IVandActivity getActivities(int index) {
      return activities_.get(index);
    }
    /**
     * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder getActivitiesOrBuilder(
        int index) {
      return activities_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      for (int i = 0; i < activities_.size(); i++) {
        output.writeMessage(2, activities_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      for (int i = 0; i < activities_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, activities_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse other = (net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!getActivitiesList()
          .equals(other.getActivitiesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (getActivitiesCount() > 0) {
        hash = (37 * hash) + ACTIVITIES_FIELD_NUMBER;
        hash = (53 * hash) + getActivitiesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.iGap.proto.UserIVandGetActivitiesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.iGap.proto.UserIVandGetActivitiesResponse)
        net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivitiesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivitiesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse.class, net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse.Builder.class);
      }

      // Construct using net.iGap.net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getActivitiesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        if (activitiesBuilder_ == null) {
          activities_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          activitiesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoUserIVandGetActivities.internal_static_proto_UserIVandGetActivitiesResponse_descriptor;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse getDefaultInstanceForType() {
        return net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse build() {
        net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse buildPartial() {
        net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse result = new net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse(this);
        int from_bitField0_ = bitField0_;
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (activitiesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            activities_ = java.util.Collections.unmodifiableList(activities_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.activities_ = activities_;
        } else {
          result.activities_ = activitiesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse) {
          return mergeFrom((net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse other) {
        if (other == net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (activitiesBuilder_ == null) {
          if (!other.activities_.isEmpty()) {
            if (activities_.isEmpty()) {
              activities_ = other.activities_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureActivitiesIsMutable();
              activities_.addAll(other.activities_);
            }
            onChanged();
          }
        } else {
          if (!other.activities_.isEmpty()) {
            if (activitiesBuilder_.isEmpty()) {
              activitiesBuilder_.dispose();
              activitiesBuilder_ = null;
              activities_ = other.activities_;
              bitField0_ = (bitField0_ & ~0x00000001);
              activitiesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getActivitiesFieldBuilder() : null;
            } else {
              activitiesBuilder_.addAllMessages(other.activities_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private net.iGap.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       * @return The response.
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private java.util.List<net.iGap.proto.ProtoGlobal.IVandActivity> activities_ =
        java.util.Collections.emptyList();
      private void ensureActivitiesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          activities_ = new java.util.ArrayList<net.iGap.proto.ProtoGlobal.IVandActivity>(activities_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.IVandActivity, net.iGap.proto.ProtoGlobal.IVandActivity.Builder, net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder> activitiesBuilder_;

      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public java.util.List<net.iGap.proto.ProtoGlobal.IVandActivity> getActivitiesList() {
        if (activitiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(activities_);
        } else {
          return activitiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public int getActivitiesCount() {
        if (activitiesBuilder_ == null) {
          return activities_.size();
        } else {
          return activitiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.IVandActivity getActivities(int index) {
        if (activitiesBuilder_ == null) {
          return activities_.get(index);
        } else {
          return activitiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder setActivities(
          int index, net.iGap.proto.ProtoGlobal.IVandActivity value) {
        if (activitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivitiesIsMutable();
          activities_.set(index, value);
          onChanged();
        } else {
          activitiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder setActivities(
          int index, net.iGap.proto.ProtoGlobal.IVandActivity.Builder builderForValue) {
        if (activitiesBuilder_ == null) {
          ensureActivitiesIsMutable();
          activities_.set(index, builderForValue.build());
          onChanged();
        } else {
          activitiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder addActivities(net.iGap.proto.ProtoGlobal.IVandActivity value) {
        if (activitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivitiesIsMutable();
          activities_.add(value);
          onChanged();
        } else {
          activitiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder addActivities(
          int index, net.iGap.proto.ProtoGlobal.IVandActivity value) {
        if (activitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivitiesIsMutable();
          activities_.add(index, value);
          onChanged();
        } else {
          activitiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder addActivities(
          net.iGap.proto.ProtoGlobal.IVandActivity.Builder builderForValue) {
        if (activitiesBuilder_ == null) {
          ensureActivitiesIsMutable();
          activities_.add(builderForValue.build());
          onChanged();
        } else {
          activitiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder addActivities(
          int index, net.iGap.proto.ProtoGlobal.IVandActivity.Builder builderForValue) {
        if (activitiesBuilder_ == null) {
          ensureActivitiesIsMutable();
          activities_.add(index, builderForValue.build());
          onChanged();
        } else {
          activitiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder addAllActivities(
          java.lang.Iterable<? extends net.iGap.proto.ProtoGlobal.IVandActivity> values) {
        if (activitiesBuilder_ == null) {
          ensureActivitiesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, activities_);
          onChanged();
        } else {
          activitiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder clearActivities() {
        if (activitiesBuilder_ == null) {
          activities_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          activitiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public Builder removeActivities(int index) {
        if (activitiesBuilder_ == null) {
          ensureActivitiesIsMutable();
          activities_.remove(index);
          onChanged();
        } else {
          activitiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.IVandActivity.Builder getActivitiesBuilder(
          int index) {
        return getActivitiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder getActivitiesOrBuilder(
          int index) {
        if (activitiesBuilder_ == null) {
          return activities_.get(index);  } else {
          return activitiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public java.util.List<? extends net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder>
           getActivitiesOrBuilderList() {
        if (activitiesBuilder_ != null) {
          return activitiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(activities_);
        }
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.IVandActivity.Builder addActivitiesBuilder() {
        return getActivitiesFieldBuilder().addBuilder(
            net.iGap.proto.ProtoGlobal.IVandActivity.getDefaultInstance());
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public net.iGap.proto.ProtoGlobal.IVandActivity.Builder addActivitiesBuilder(
          int index) {
        return getActivitiesFieldBuilder().addBuilder(
            index, net.iGap.proto.ProtoGlobal.IVandActivity.getDefaultInstance());
      }
      /**
       * <code>repeated .net.iGap.proto.IVandActivity activities = 2;</code>
       */
      public java.util.List<net.iGap.proto.ProtoGlobal.IVandActivity.Builder>
           getActivitiesBuilderList() {
        return getActivitiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.iGap.proto.ProtoGlobal.IVandActivity, net.iGap.proto.ProtoGlobal.IVandActivity.Builder, net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder>
          getActivitiesFieldBuilder() {
        if (activitiesBuilder_ == null) {
          activitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.iGap.proto.ProtoGlobal.IVandActivity, net.iGap.proto.ProtoGlobal.IVandActivity.Builder, net.iGap.proto.ProtoGlobal.IVandActivityOrBuilder>(
                  activities_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          activities_ = null;
        }
        return activitiesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.iGap.proto.UserIVandGetActivitiesResponse)
    }

    // @@protoc_insertion_point(class_scope:net.iGap.proto.UserIVandGetActivitiesResponse)
    private static final net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse();
    }

    public static net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserIVandGetActivitiesResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserIVandGetActivitiesResponse>() {
      @java.lang.Override
      public UserIVandGetActivitiesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserIVandGetActivitiesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserIVandGetActivitiesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserIVandGetActivitiesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.iGap.proto.ProtoUserIVandGetActivities.UserIVandGetActivitiesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserIVandGetActivities_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserIVandGetActivities_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserIVandGetActivitiesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserIVandGetActivitiesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034UserIVandGetActivities.net.iGap.proto\022\005proto\032\rR" +
      "equest.net.iGap.proto\032\016Response.net.iGap.proto\032\014Global.pro" +
      "to\"`\n\026UserIVandGetActivities\022\037\n\007request\030" +
      "\001 \001(\0132\016.net.iGap.proto.Request\022%\n\npagination\030\002 \001(" +
      "\0132\021.net.iGap.proto.Pagination\"m\n\036UserIVandGetActi" +
      "vitiesResponse\022!\n\010response\030\001 \001(\0132\017.net.iGap.proto" +
      ".Response\022(\n\nactivities\030\002 \003(\0132\024.net.iGap.proto.IV" +
      "andActivityB5\n\026net.iGap.protoB\033P" +
      "rotoUserIVandGetActivitiesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.iGap.proto.ProtoRequest.getDescriptor(),
          net.iGap.proto.ProtoResponse.getDescriptor(),
          net.iGap.proto.ProtoGlobal.getDescriptor(),
        });
    internal_static_proto_UserIVandGetActivities_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_UserIVandGetActivities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserIVandGetActivities_descriptor,
        new java.lang.String[] { "Request", "Pagination", });
    internal_static_proto_UserIVandGetActivitiesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_UserIVandGetActivitiesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserIVandGetActivitiesResponse_descriptor,
        new java.lang.String[] { "Response", "Activities", });
    net.iGap.proto.ProtoRequest.getDescriptor();
    net.iGap.proto.ProtoResponse.getDescriptor();
    net.iGap.proto.ProtoGlobal.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
