// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChannelAddMessageReaction.net.iGap.proto

package net.iGap.proto;

public final class ProtoChannelAddMessageReaction {
  private ProtoChannelAddMessageReaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChannelAddMessageReactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.iGap.proto.ChannelAddMessageReaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return The request.
     */
    net.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     */
    net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    long getRoomId();

    /**
     * <code>uint64 message_id = 3;</code>
     * @return The messageId.
     */
    long getMessageId();

    /**
     * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
     * @return The enum numeric value on the wire for reaction.
     */
    int getReactionValue();
    /**
     * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
     * @return The reaction.
     */
    net.iGap.proto.ProtoGlobal.RoomMessageReaction getReaction();

    /**
     * <code>uint64 document_id = 5;</code>
     * @return The documentId.
     */
    long getDocumentId();
  }
  /**
   * Protobuf type {@code net.iGap.proto.ChannelAddMessageReaction}
   */
  public static final class ChannelAddMessageReaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.iGap.proto.ChannelAddMessageReaction)
      ChannelAddMessageReactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChannelAddMessageReaction.newBuilder() to construct.
    private ChannelAddMessageReaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelAddMessageReaction() {
      reaction_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChannelAddMessageReaction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChannelAddMessageReaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomId_ = input.readUInt64();
              break;
            }
            case 24: {

              messageId_ = input.readUInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              reaction_ = rawValue;
              break;
            }
            case 40: {

              documentId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction.class, net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     * @return The request.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.net.iGap.proto.Request request = 1;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int ROOM_ID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    @java.lang.Override
    public long getRoomId() {
      return roomId_;
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 3;
    private long messageId_;
    /**
     * <code>uint64 message_id = 3;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public long getMessageId() {
      return messageId_;
    }

    public static final int REACTION_FIELD_NUMBER = 4;
    private int reaction_;
    /**
     * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
     * @return The enum numeric value on the wire for reaction.
     */
    @java.lang.Override public int getReactionValue() {
      return reaction_;
    }
    /**
     * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
     * @return The reaction.
     */
    @java.lang.Override public net.iGap.proto.ProtoGlobal.RoomMessageReaction getReaction() {
      @SuppressWarnings("deprecation")
      net.iGap.proto.ProtoGlobal.RoomMessageReaction result = net.iGap.proto.ProtoGlobal.RoomMessageReaction.valueOf(reaction_);
      return result == null ? net.iGap.proto.ProtoGlobal.RoomMessageReaction.UNRECOGNIZED : result;
    }

    public static final int DOCUMENT_ID_FIELD_NUMBER = 5;
    private long documentId_;
    /**
     * <code>uint64 document_id = 5;</code>
     * @return The documentId.
     */
    @java.lang.Override
    public long getDocumentId() {
      return documentId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (roomId_ != 0L) {
        output.writeUInt64(2, roomId_);
      }
      if (messageId_ != 0L) {
        output.writeUInt64(3, messageId_);
      }
      if (reaction_ != net.iGap.proto.ProtoGlobal.RoomMessageReaction.THUMBS_UP.getNumber()) {
        output.writeEnum(4, reaction_);
      }
      if (documentId_ != 0L) {
        output.writeUInt64(5, documentId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, roomId_);
      }
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, messageId_);
      }
      if (reaction_ != net.iGap.proto.ProtoGlobal.RoomMessageReaction.THUMBS_UP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, reaction_);
      }
      if (documentId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, documentId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction other = (net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (getRoomId()
          != other.getRoomId()) return false;
      if (getMessageId()
          != other.getMessageId()) return false;
      if (reaction_ != other.reaction_) return false;
      if (getDocumentId()
          != other.getDocumentId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (37 * hash) + REACTION_FIELD_NUMBER;
      hash = (53 * hash) + reaction_;
      hash = (37 * hash) + DOCUMENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDocumentId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.iGap.proto.ChannelAddMessageReaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.iGap.proto.ChannelAddMessageReaction)
        net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction.class, net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction.Builder.class);
      }

      // Construct using net.iGap.net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        roomId_ = 0L;

        messageId_ = 0L;

        reaction_ = 0;

        documentId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReaction_descriptor;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction getDefaultInstanceForType() {
        return net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction.getDefaultInstance();
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction build() {
        net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction buildPartial() {
        net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction result = new net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.roomId_ = roomId_;
        result.messageId_ = messageId_;
        result.reaction_ = reaction_;
        result.documentId_ = documentId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction) {
          return mergeFrom((net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction other) {
        if (other == net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        if (other.reaction_ != 0) {
          setReactionValue(other.getReactionValue());
        }
        if (other.getDocumentId() != 0L) {
          setDocumentId(other.getDocumentId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       * @return The request.
       */
      public net.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder setRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              net.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      public net.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.net.iGap.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoRequest.Request, net.iGap.proto.ProtoRequest.Request.Builder, net.iGap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long roomId_ ;
      /**
       * <code>uint64 room_id = 2;</code>
       * @return The roomId.
       */
      @java.lang.Override
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }

      private long messageId_ ;
      /**
       * <code>uint64 message_id = 3;</code>
       * @return The messageId.
       */
      @java.lang.Override
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>uint64 message_id = 3;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(long value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 message_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private int reaction_ = 0;
      /**
       * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
       * @return The enum numeric value on the wire for reaction.
       */
      @java.lang.Override public int getReactionValue() {
        return reaction_;
      }
      /**
       * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
       * @param value The enum numeric value on the wire for reaction to set.
       * @return This builder for chaining.
       */
      public Builder setReactionValue(int value) {
        
        reaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
       * @return The reaction.
       */
      @java.lang.Override
      public net.iGap.proto.ProtoGlobal.RoomMessageReaction getReaction() {
        @SuppressWarnings("deprecation")
        net.iGap.proto.ProtoGlobal.RoomMessageReaction result = net.iGap.proto.ProtoGlobal.RoomMessageReaction.valueOf(reaction_);
        return result == null ? net.iGap.proto.ProtoGlobal.RoomMessageReaction.UNRECOGNIZED : result;
      }
      /**
       * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
       * @param value The reaction to set.
       * @return This builder for chaining.
       */
      public Builder setReaction(net.iGap.proto.ProtoGlobal.RoomMessageReaction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        reaction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.net.iGap.proto.RoomMessageReaction reaction = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReaction() {
        
        reaction_ = 0;
        onChanged();
        return this;
      }

      private long documentId_ ;
      /**
       * <code>uint64 document_id = 5;</code>
       * @return The documentId.
       */
      @java.lang.Override
      public long getDocumentId() {
        return documentId_;
      }
      /**
       * <code>uint64 document_id = 5;</code>
       * @param value The documentId to set.
       * @return This builder for chaining.
       */
      public Builder setDocumentId(long value) {
        
        documentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 document_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDocumentId() {
        
        documentId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.iGap.proto.ChannelAddMessageReaction)
    }

    // @@protoc_insertion_point(class_scope:net.iGap.proto.ChannelAddMessageReaction)
    private static final net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction();
    }

    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChannelAddMessageReaction>
        PARSER = new com.google.protobuf.AbstractParser<ChannelAddMessageReaction>() {
      @java.lang.Override
      public ChannelAddMessageReaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelAddMessageReaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChannelAddMessageReaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelAddMessageReaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChannelAddMessageReactionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.iGap.proto.ChannelAddMessageReactionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return The response.
     */
    net.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     */
    net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>string reaction_counter_label = 2;</code>
     * @return The reactionCounterLabel.
     */
    java.lang.String getReactionCounterLabel();
    /**
     * <code>string reaction_counter_label = 2;</code>
     * @return The bytes for reactionCounterLabel.
     */
    com.google.protobuf.ByteString
        getReactionCounterLabelBytes();
  }
  /**
   * Protobuf type {@code net.iGap.proto.ChannelAddMessageReactionResponse}
   */
  public static final class ChannelAddMessageReactionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.iGap.proto.ChannelAddMessageReactionResponse)
      ChannelAddMessageReactionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChannelAddMessageReactionResponse.newBuilder() to construct.
    private ChannelAddMessageReactionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelAddMessageReactionResponse() {
      reactionCounterLabel_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChannelAddMessageReactionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChannelAddMessageReactionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              reactionCounterLabel_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReactionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReactionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse.class, net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     * @return The response.
     */
    @java.lang.Override
    public net.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.net.iGap.proto.Response response = 1;</code>
     */
    @java.lang.Override
    public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int REACTION_COUNTER_LABEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object reactionCounterLabel_;
    /**
     * <code>string reaction_counter_label = 2;</code>
     * @return The reactionCounterLabel.
     */
    @java.lang.Override
    public java.lang.String getReactionCounterLabel() {
      java.lang.Object ref = reactionCounterLabel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reactionCounterLabel_ = s;
        return s;
      }
    }
    /**
     * <code>string reaction_counter_label = 2;</code>
     * @return The bytes for reactionCounterLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReactionCounterLabelBytes() {
      java.lang.Object ref = reactionCounterLabel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reactionCounterLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (!getReactionCounterLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reactionCounterLabel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (!getReactionCounterLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reactionCounterLabel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse)) {
        return super.equals(obj);
      }
      net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse other = (net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!getReactionCounterLabel()
          .equals(other.getReactionCounterLabel())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + REACTION_COUNTER_LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getReactionCounterLabel().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.iGap.proto.ChannelAddMessageReactionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.iGap.proto.ChannelAddMessageReactionResponse)
        net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReactionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReactionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse.class, net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse.Builder.class);
      }

      // Construct using net.iGap.net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        reactionCounterLabel_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.iGap.proto.ProtoChannelAddMessageReaction.internal_static_proto_ChannelAddMessageReactionResponse_descriptor;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse getDefaultInstanceForType() {
        return net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse build() {
        net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse buildPartial() {
        net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse result = new net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.reactionCounterLabel_ = reactionCounterLabel_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse) {
          return mergeFrom((net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse other) {
        if (other == net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (!other.getReactionCounterLabel().isEmpty()) {
          reactionCounterLabel_ = other.reactionCounterLabel_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.iGap.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       * @return The response.
       */
      public net.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder setResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              net.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      public net.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.net.iGap.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.iGap.proto.ProtoResponse.Response, net.iGap.proto.ProtoResponse.Response.Builder, net.iGap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private java.lang.Object reactionCounterLabel_ = "";
      /**
       * <code>string reaction_counter_label = 2;</code>
       * @return The reactionCounterLabel.
       */
      public java.lang.String getReactionCounterLabel() {
        java.lang.Object ref = reactionCounterLabel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reactionCounterLabel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reaction_counter_label = 2;</code>
       * @return The bytes for reactionCounterLabel.
       */
      public com.google.protobuf.ByteString
          getReactionCounterLabelBytes() {
        java.lang.Object ref = reactionCounterLabel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reactionCounterLabel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reaction_counter_label = 2;</code>
       * @param value The reactionCounterLabel to set.
       * @return This builder for chaining.
       */
      public Builder setReactionCounterLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reactionCounterLabel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reaction_counter_label = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReactionCounterLabel() {
        
        reactionCounterLabel_ = getDefaultInstance().getReactionCounterLabel();
        onChanged();
        return this;
      }
      /**
       * <code>string reaction_counter_label = 2;</code>
       * @param value The bytes for reactionCounterLabel to set.
       * @return This builder for chaining.
       */
      public Builder setReactionCounterLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reactionCounterLabel_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.iGap.proto.ChannelAddMessageReactionResponse)
    }

    // @@protoc_insertion_point(class_scope:net.iGap.proto.ChannelAddMessageReactionResponse)
    private static final net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse();
    }

    public static net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChannelAddMessageReactionResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChannelAddMessageReactionResponse>() {
      @java.lang.Override
      public ChannelAddMessageReactionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelAddMessageReactionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChannelAddMessageReactionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelAddMessageReactionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.iGap.proto.ProtoChannelAddMessageReaction.ChannelAddMessageReactionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChannelAddMessageReaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChannelAddMessageReaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChannelAddMessageReactionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChannelAddMessageReactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037ChannelAddMessageReaction.net.iGap.proto\022\005proto" +
      "\032\rRequest.net.iGap.proto\032\016Response.net.iGap.proto\032\014Global." +
      "net.iGap.proto\"\244\001\n\031ChannelAddMessageReaction\022\037\n\007r" +
      "equest\030\001 \001(\0132\016.net.iGap.proto.Request\022\017\n\007room_id\030" +
      "\002 \001(\004\022\022\n\nmessage_id\030\003 \001(\004\022,\n\010reaction\030\004 " +
      "\001(\0162\032.net.iGap.proto.RoomMessageReaction\022\023\n\013docum" +
      "ent_id\030\005 \001(\004\"f\n!ChannelAddMessageReactio" +
      "nResponse\022!\n\010response\030\001 \001(\0132\017.net.iGap.proto.Resp" +
      "onse\022\036\n\026reaction_counter_label\030\002 \001(\tB8\n\026" +
      "net.iGap.protoB\036ProtoChannelAddM" +
      "essageReactionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.iGap.proto.ProtoRequest.getDescriptor(),
          net.iGap.proto.ProtoResponse.getDescriptor(),
          net.iGap.proto.ProtoGlobal.getDescriptor(),
        });
    internal_static_proto_ChannelAddMessageReaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ChannelAddMessageReaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChannelAddMessageReaction_descriptor,
        new java.lang.String[] { "Request", "RoomId", "MessageId", "Reaction", "DocumentId", });
    internal_static_proto_ChannelAddMessageReactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ChannelAddMessageReactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChannelAddMessageReactionResponse_descriptor,
        new java.lang.String[] { "Response", "ReactionCounterLabel", });
    net.iGap.proto.ProtoRequest.getDescriptor();
    net.iGap.proto.ProtoResponse.getDescriptor();
    net.iGap.proto.ProtoGlobal.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
